# Generated by Django 4.2.6 on 2024-06-23 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_post_user_post_profile_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('owner', 'post')},
        ),
    ]
