# Generated by Django 4.2.6 on 2024-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_likepost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='likepost_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
