# Generated by Django 4.2.6 on 2024-06-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_likepost_likepost_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='likepost_id',
        ),
    ]
