# Generated by Django 4.2.6 on 2024-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_likepost_likepost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default_cover_image.jpg', null=True, upload_to='cover_images/'),
        ),
    ]
