# Generated by Django 4.2.6 on 2024-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_followerscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
